# Site settings
title: Research Tips & Strategies
email: uclawire@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 The WI+RE team develops and continually improves a toolbox of open-access online learning modules that can be used by both instructors and students.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: wirebruin
github_username:  uclalibrary
facebook_username: wirebruin

# Build settings
markdown: kramdown
